<img src="Logo.png" width="100" align="left"/> 

# <center> Unit 3 Project </center>
#  <center> Third section : supervised task </center>

In this notebook you will be building and training a supervised learning model to classify your data.

For this task we will be using another classification model "The random forests" model.

Steps for this task: 
1. Load the already clustered dataset 
2. Take into consideration that in this task we will not be using the already added column "Cluster" 
3. Split your data.
3. Build your model using the SKlearn RandomForestClassifier class 
4. classify your data and test the performance of your model 
5. Evaluate the model ( accepted models should have at least an accuracy of 86%). Play with hyper parameters and provide a report about that.
6. Provide evidence on the quality of your model (not overfitted good metrics)
7. Create a new test dataset that contains the testset + an additional column called "predicted_class" stating the class predicted by your random forest classifier for each data point of the test set.

## 1. Load the data and split the data:

In [1]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd 
from sklearn.model_selection import train_test_split

In [2]:
# To-Do:  load the data 
df = pd.read_csv('clustered_HepatitisC.csv')
df.head()

,ID,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,cluster
0,1,0=Blood Donor,32,1,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0,3
1,2,0=Blood Donor,32,1,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5,3
2,3,0=Blood Donor,32,1,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3,3
3,4,0=Blood Donor,32,1,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7,3
4,5,0=Blood Donor,32,1,39.2,74.1,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7,3

In [160]:
# To-Do : keep only the columns to be used : all features except ID, cluster 
# The target here is the Category column 
# Do not forget to split your data (this is a classification task)
# test set size should be 20% of the data

In [3]:
# Feature Selection

X = df.drop(columns=['ID','cluster','Category'])
y = df['Category']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(492, 12)
(123, 12)

## 2. Building the model and training and evaluate the performance:

In [ ]:
# To-do build the model and train it 
# note that you will be providing explanation about the hyper parameter tuning 
# So you will be iterating a number of times before getting the desired performance

## 3. Build and Train Random Forest

Hyperparameters selected:

- n_estimators = 100
- max_depth = 8
- min_samples_split = 5
- random_state = 42

In [4]:
rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=8,
    min_samples_split=5,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, min_samples_split=5, random_state=42)

In [5]:
y_hat = rf.predict(X_test)
y_hat[:10]

array(['0=Blood Donor', '0=Blood Donor', '0=Blood Donor', '0=Blood Donor',
       '0=Blood Donor', '0=Blood Donor', '0=Blood Donor', '0=Blood Donor',
       '0=Blood Donor', '0=Blood Donor'], dtype=object)

In [6]:
# To-do : evaluate the model in terms of accuracy and precision 
# Provide evidence that your model is not overfitting 
from sklearn.metrics import precision_score, accuracy_score

test_accuracy = accuracy_score(y_test, y_hat)
test_precision = precision_score(y_test, y_hat, average='weighted')

train_accuracy = accuracy_score(y_train, rf.predict(X_train))

print("Train Accuracy:", round(train_accuracy,4))
print("Test Accuracy :", round(test_accuracy,4))
print("Precision     :", round(test_precision,4))

print("\nDifference:", round(train_accuracy-test_accuracy,4))

Train Accuracy: 0.9919
Test Accuracy : 0.9431
Precision     : 0.9294

Difference: 0.0488

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

> Hint : A Perfect accuracy on the train set suggest that we have an overfitted model So the student should be able to provide a detailed table about the hyper parameters / parameters tuning with a good conclusion stating that the model has at least an accuracy of 86% on the test set without signs of overfitting

## 3. Create the summary test set with the additional predicted class column: 
In this part you need to add the predicted class as a column to your test dataframe and save this one

In [14]:
# To-Do : create the complete test dataframe : it should contain all the feature column + the actual target and the ID as well  
#test_df = X_test.copy()

test_df['Category'] = y_test.values

In [15]:
test_df.head()

,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,Category,Predicted_class
270,59,1,39.8,49.4,25.4,21.4,24.7,7.50,3.69,86.0,18.7,71.9,0=Blood Donor,0=Blood Donor
454,51,0,38.3,52.9,12.4,16.5,3.8,7.22,5.43,55.0,12.7,70.2,0=Blood Donor,0=Blood Donor
235,53,1,49.2,71.8,42.8,29.4,6.8,15.10,6.24,107.0,48.3,77.8,0=Blood Donor,0=Blood Donor
470,52,0,36.7,87.6,34.3,30.8,17.7,10.12,6.98,72.0,24.2,66.3,0=Blood Donor,0=Blood Donor
58,37,1,44.8,94.3,32.2,36.7,6.3,9.76,4.12,113.0,23.8,72.5,0=Blood Donor,0=Blood Donor

In [16]:
# To-Do : Add the predicted_class column 
test_df['Predicted_class'] = y_hat

In [17]:
test_df.head()

,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,Category,Predicted_class
270,59,1,39.8,49.4,25.4,21.4,24.7,7.50,3.69,86.0,18.7,71.9,0=Blood Donor,0=Blood Donor
454,51,0,38.3,52.9,12.4,16.5,3.8,7.22,5.43,55.0,12.7,70.2,0=Blood Donor,0=Blood Donor
235,53,1,49.2,71.8,42.8,29.4,6.8,15.10,6.24,107.0,48.3,77.8,0=Blood Donor,0=Blood Donor
470,52,0,36.7,87.6,34.3,30.8,17.7,10.12,6.98,72.0,24.2,66.3,0=Blood Donor,0=Blood Donor
58,37,1,44.8,94.3,32.2,36.7,6.3,9.76,4.12,113.0,23.8,72.5,0=Blood Donor,0=Blood Donor

> Make sure you have 16 column in this test set

In [18]:
# Save the test set 
test_df.to_csv("test_summary.csv")